### ISSUE TITLE
Phantasy Star Online Plus Support

### ISSUE THREAD

**Issue by shanafan** [suloku/gcmm#28]
In version 1.3, I read that PSO support was added for their serial protected saves.

When I copied over my saves for PSO Plus, my game couldn't find it. Would this be true? There is support for PSO, but not PSO Plus?

Thanks!

**Comment by suloku** [comment]
I tested pso 1&2 and pso 3, all regions.

I didn't know about pso plus, probably it uses a different gamecode, but the save structure is the same. Can you upload a pso+ savegame?

**Comment by shanafan** [comment]
Thanks for the response!

I eventually did get it to work. I had to do a workaround, though. I used Dolphin to convert the raw saved game into 3 separate GCI files onto a USB flash drive, and then I uploaded those from USB flash drive to my GCN memory card using GCMM. So, I did get it working, just needed to use Dolphin to convert the saves to GCI.

Thanks for GCMM!

**Comment by suloku** [comment]
Can I get the original raw files? That means there's something wrong with the internal raw->gci conversion rather than with the serial code protection patching.

**Comment by shanafan** [comment]
Sure. I have attached a ZIP file of the RAW file.
[GPOE.zip](https://github.com/suloku/gcmm/files/235701/GPOE.zip)

**Comment by suloku** [comment]
Seems I kind of forgot about this... sorry. On further reading, it seems to me that you where originally trying to restore a raw memory card file with all the saves and that's what wasn't working, then after converting to GCI everything was fine.

That's expected behaviour, a raw memory card restore copies over everything, but won't check any saves in the image and won't fix PSO (or F-zero) savegames, these savegames require to be copied as GCI files for GCMM to fix them for the new memory card serial number.

As a side note, a raw image of an unofficial memory card copied over another unofficial memory card should have worked, as unoficial memory cards normally have the same serial number (all zeroes), or at least all the unofficial ones I've the chance to check.
